name: Docker
on: push
jobs:
  push:
    name: Pushs into Docker Hub
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v5
      - id: setup-qemu
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - id: setup-buildx
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - id: login
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: build-and-push
        name: Build a docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tmatsudate/gauche-cli:latest
